# This is a basic workflow that is manually triggered

name: First Workflow Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # runs a job called test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
    - name: Run script
      run: bash weather_api.py
