# This is a basic workflow that is manually triggered

name: First Workflow Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repository to the runner
       uses: actions/checkout@v2


     - name: Set up Python
       uses: actions/setup-python@v4.7.1
       with:
         python-version: '3.10'
         
     - name: Install packages
       run: |
         python -m pip install requests
         pip install influxdb3-python
         
       
     
     - name: Run script
       run: python scripts/weather_api.py
